let res = {
	"msg": "操作成功",
	"code": 0,
	"org": [{
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 11:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": "",
		"params": {},
		"postId": 1,
		"postCode": "ceo",
		"postName": "董事长",
		"postSort": "1",
		"status": "0",
		"flag": true
	}, {
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 11:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": "",
		"params": {},
		"postId": 2,
		"postCode": "se",
		"postName": "项目经理",
		"postSort": "2",
		"status": "0",
		"flag": false
	}, {
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 11:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": "",
		"params": {},
		"postId": 3,
		"postCode": "hr",
		"postName": "人力资源",
		"postSort": "3",
		"status": "0",
		"flag": false
	}, {
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 11:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": "",
		"params": {},
		"postId": 4,
		"postCode": "user",
		"postName": "普通员工",
		"postSort": "4",
		"status": "0",
		"flag": false
	}],
	"permissions": ["system:user:resetPwd", "system:post:list", "monitor:operlog:export", "system:post:view", "system:dept:remove", "system:menu:list", "tool:gen:edit", "system:dict:edit", "monitor:logininfor:remove", "monitor:job:list", "system:dict:view", "system:user:add", "carbon:chargingPileDevice:view", "system:user:export", "system:role:remove", "monitor:job:edit", "monitor:logininfor:view", "carbon:chargingPileDevice:list", "system:menu:view", "carbon:capacityDeclarationConfig:add", "system:dict:list", "carbon:photovoltaicDevice:add", "carbon:photovoltaicDevice:edit", "monitor:online:forceLogout", "monitor:online:view", "carbon:photovoltaicDevice:list", "tool:gen:view", "monitor:online:list", "system:post:edit", "monitor:job:add", "monitor:logininfor:list", "carbon:capacityDeclarationConfig:view", "monitor:job:view", "carbon:capacityDeclarationConfig:list", "tool:gen:list", "carbon:photovoltaicDevice:view", "system:dict:export", "system:post:remove", "carbon:chargingPileDevice:edit", "carbon:capacityDeclarationConfig:remove", "tool:swagger:view", "system:user:remove", "system:menu:add", "system:role:list", "monitor:job:detail", "system:user:import", "system:dict:remove", "system:role:view", "system:user:edit", "system:post:export", "system:role:edit", "monitor:operlog:view", "system:dept:list", "monitor:server:view", "system:dept:view", "monitor:data:view", "monitor:operlog:remove", "monitor:operlog:list", "system:role:add", "carbon:capacityDeclarationConfig:edit", "system:menu:remove", "system:dict:add", "monitor:logininfor:export", "system:dept:edit", "system:post:add", "monitor:job:changeStatus", "carbon:chargingPileDevice:add", "tool:gen:preview", "system:user:view", "carbon:photovoltaicDevice:remove", "system:user:list", "carbon:chargingPileDevice:remove", "monitor:job:remove", "system:role:export", "monitor:operlog:detail", "monitor:online:batchForceLogout", "tool:gen:code", "monitor:job:export", "tool:gen:remove", "system:menu:edit", "system:dept:add"],
	"roles": ["admin"],
	"user": {
		"searchValue": null,
		"createBy": null,
		"createTime": "2022-03-02 11:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": "管理员",
		"params": {},
		"userId": 1,
		"deptId": 103,
		"parentId": null,
		"roleId": null,
		"loginName": "admin",
		"userName": "admin",
		"email": "",
		"phonenumber": "",
		"sex": "0",
		"avatar": "/profile/avatar/2022/03/05/fe350f40ba56fff1066e9a267b031459.png",
		"password": "338bffe3cf5895802db57bd6861e0e14",
		"salt": "09faf7",
		"status": "0",
		"delFlag": "0",
		"loginIp": "",
		"loginDate": "2022-04-12 15:35:50",
		"dept": {
			"searchValue": null,
			"createBy": null,
			"createTime": null,
			"updateBy": null,
			"updateTime": null,
			"remark": null,
			"params": {},
			"deptId": 103,
			"parentId": 101,
			"ancestors": null,
			"deptName": "研发部",
			"orderNum": "1",
			"leader": "SE",
			"phone": null,
			"email": null,
			"status": "0",
			"delFlag": null,
			"parentName": null
		},
		"roles": [{
			"searchValue": null,
			"createBy": null,
			"createTime": null,
			"updateBy": null,
			"updateTime": null,
			"remark": null,
			"params": {},
			"roleId": 1,
			"roleName": "管理员",
			"roleKey": "admin",
			"roleSort": "1",
			"dataScope": "1",
			"status": "0",
			"delFlag": null,
			"flag": false,
			"menuIds": null,
			"deptIds": null
		}],
		"roleIds": null,
		"postIds": null,
		"admin": true
	}
}
export default res