let modelUrl= [
    {
        url:"/mobileData/mobileModel/leftUnder.gltf",
        name:"leftUnder",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    
    {
        url:"/mobileData/mobileModel/lingNengSheBei.gltf",
        name:"lingNengSheBei",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/leftMiddle.gltf",
        name:"leftMiddle",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/rightUnder.gltf",
        name:"rightUnder",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/rightMiddle.gltf",
        name:"rightMiddle",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/bridge.gltf",
        name:"bridge",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/caodi1.gltf",
        name:"caodi",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/rightTop.gltf",
        name:"rightTop",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    },
    {
        url:"/mobileData/mobileModel/leftTop.gltf",
        name:"leftTop",
        scale:{
            x:0.2,
            y:0.2,
            z:0.2
        },
        materialType:"false"
    }
    
]

export {modelUrl}